// This file is @generated by wasmcloud/weld-codegen 0.7.0.
// It is not intended for manual editing.
// namespace: org.cosmonic.wasmcon.waveshareoled

#[allow(unused_imports)]
use async_trait::async_trait;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use std::{borrow::Borrow, borrow::Cow, io::Write, string::ToString};
#[allow(unused_imports)]
use wasmbus_rpc::{
    cbor::*,
    common::{
        deserialize, message_format, serialize, Context, Message, MessageDispatch, MessageFormat,
        SendOpts, Transport,
    },
    error::{RpcError, RpcResult},
    Timestamp,
};

#[allow(dead_code)]
pub const SMITHY_VERSION: &str = "1.0";

#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct DrawMessageInput {
    #[serde(default)]
    pub message: String,
}

// Encode DrawMessageInput as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_draw_message_input<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &DrawMessageInput,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.map(1)?;
    e.str("message")?;
    e.str(&val.message)?;
    Ok(())
}

// Decode DrawMessageInput from cbor input stream
#[doc(hidden)]
pub fn decode_draw_message_input(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<DrawMessageInput, RpcError> {
    let __result = {
        let mut message: Option<String> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct DrawMessageInput, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => message = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "message" => message = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        }
        DrawMessageInput {
            message: if let Some(__x) = message {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field DrawMessageInput.message (#0)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
/// The Waveshareoled service has a single method, calculate, which
/// calculates the factorial of its whole number parameter.
/// wasmbus.contractId: cosmonic:waveshareoled
/// wasmbus.providerReceive
/// wasmbus.actorReceive
#[async_trait]
pub trait Waveshareoled {
    /// returns the capability contract id for this interface
    fn contract_id() -> &'static str {
        "cosmonic:waveshareoled"
    }
    /// Draws the given message on the OLED display
    async fn draw_message(&self, ctx: &Context, arg: &DrawMessageInput) -> RpcResult<()>;
}

/// WaveshareoledReceiver receives messages defined in the Waveshareoled service trait
/// The Waveshareoled service has a single method, calculate, which
/// calculates the factorial of its whole number parameter.
#[doc(hidden)]
#[async_trait]
pub trait WaveshareoledReceiver: MessageDispatch + Waveshareoled {
    async fn dispatch(&self, ctx: &Context, message: Message<'_>) -> Result<Vec<u8>, RpcError> {
        match message.method {
            "DrawMessage" => {
                let value: DrawMessageInput = wasmbus_rpc::common::deserialize(&message.arg)
                    .map_err(|e| RpcError::Deser(format!("'DrawMessageInput': {}", e)))?;

                let _resp = Waveshareoled::draw_message(self, ctx, &value).await?;
                let buf = Vec::new();
                Ok(buf)
            }
            _ => Err(RpcError::MethodNotHandled(format!(
                "Waveshareoled::{}",
                message.method
            ))),
        }
    }
}

/// WaveshareoledSender sends messages to a Waveshareoled service
/// The Waveshareoled service has a single method, calculate, which
/// calculates the factorial of its whole number parameter.
/// client for sending Waveshareoled messages
#[derive(Clone, Debug)]
pub struct WaveshareoledSender<T: Transport> {
    transport: T,
}

impl<T: Transport> WaveshareoledSender<T> {
    /// Constructs a WaveshareoledSender with the specified transport
    pub fn via(transport: T) -> Self {
        Self { transport }
    }

    pub fn set_timeout(&self, interval: std::time::Duration) {
        self.transport.set_timeout(interval);
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl<'send> WaveshareoledSender<wasmbus_rpc::provider::ProviderTransport<'send>> {
    /// Constructs a Sender using an actor's LinkDefinition,
    /// Uses the provider's HostBridge for rpc
    pub fn for_actor(ld: &'send wasmbus_rpc::core::LinkDefinition) -> Self {
        Self {
            transport: wasmbus_rpc::provider::ProviderTransport::new(ld, None),
        }
    }
}
#[cfg(target_arch = "wasm32")]
impl WaveshareoledSender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for actor-to-actor messaging
    /// using the recipient actor's public key
    pub fn to_actor(actor_id: &str) -> Self {
        let transport =
            wasmbus_rpc::actor::prelude::WasmHost::to_actor(actor_id.to_string()).unwrap();
        Self { transport }
    }
}

#[cfg(target_arch = "wasm32")]
impl WaveshareoledSender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for sending to a Waveshareoled provider
    /// implementing the 'cosmonic:waveshareoled' capability contract, with the "default" link
    pub fn new() -> Self {
        let transport =
            wasmbus_rpc::actor::prelude::WasmHost::to_provider("cosmonic:waveshareoled", "default")
                .unwrap();
        Self { transport }
    }

    /// Constructs a client for sending to a Waveshareoled provider
    /// implementing the 'cosmonic:waveshareoled' capability contract, with the specified link name
    pub fn new_with_link(link_name: &str) -> wasmbus_rpc::error::RpcResult<Self> {
        let transport = wasmbus_rpc::actor::prelude::WasmHost::to_provider(
            "cosmonic:waveshareoled",
            link_name,
        )?;
        Ok(Self { transport })
    }
}
#[async_trait]
impl<T: Transport + std::marker::Sync + std::marker::Send> Waveshareoled
    for WaveshareoledSender<T>
{
    #[allow(unused)]
    /// Draws the given message on the OLED display
    async fn draw_message(&self, ctx: &Context, arg: &DrawMessageInput) -> RpcResult<()> {
        let buf = wasmbus_rpc::common::serialize(arg)?;

        let resp = self
            .transport
            .send(
                ctx,
                Message {
                    method: "Waveshareoled.DrawMessage",
                    arg: Cow::Borrowed(&buf),
                },
                None,
            )
            .await?;
        Ok(())
    }
}
